name: Mirror to Gitee

on:
  push:
    branches: [ main, master ]
  # 可选：手动触发
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          # 支持Gitee, Github, Gitlab and Gitcode
          src: github/irritablecherry
          # 支持Gitee, Github, Gitlab and Gitcode
          dst: gitee/irritablecherry
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 支持Github/Gitee/Gitcode的用户、组织以及Gitlab的组
          account_type: user
          # 支持分别设置源和目的端的类型
          # src_account_type: org
          # dst_account_type: org
          debug: true  # 启用后会显示所有执行命令